services:
  postgres:
    image: postgres:15-alpine
    container_name: sepsis_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: SepsisNlpDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sepsis_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Porta de comunicação da API com o RabbitMQ
      - "15672:15672" # Porta da interface visual (Painel Admin)

volumes:
  postgres_data: